# Site info
site_name: Reboot Book
site_description: A Pisay-oriented introduction to computer science and the study of informatics.
site_author: Reboot
site_url: https://reboot.blubits.me

# Repository
repo_name: 'blubits/reboot-book'
repo_url: 'https://github.com/blubits/reboot-book'

# Directory info
docs_dir: 'book'
site_dir: '@site'

# Copyright
copyright: 'Copyright &copy; 2018 Reboot'

# Theme
theme:
    name: 'material'
    palette:
        primary: blue grey
        accent: red
    logo:
        icon: 'code'
    feature:
        tabs: true
extra_css:
    - 'css/book.css'

# Pages
pages:
    - Home: index.md
    - Foreword:
        - Introduction: foreword/intro.md
        - Further reading: foreword/further-reading.md
    - Module 1:
        - Index: 00-ics/index.md
        - (1.1) Solving problems: 00-ics/00-solving-problems.md

# Extensions
markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
